"""Structured incident report generator."""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path


REPORT_TEMPLATE = """
╔══════════════════════════════════════════════════════════════════════════╗
║              FIND EVIL — INCIDENT ANALYSIS REPORT                       ║
╚══════════════════════════════════════════════════════════════════════════╝

Case ID:        {case_id}
Generated:      {generated_at}
Risk Level:     {risk_level}
Total Findings: {total_findings}
Corroborated:   {corroborated_count}
Unverified:     {unverified_count}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ANALYST SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{analyst_summary}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ATTACK TIMELINE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{timeline}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CONFIRMED FINDINGS  (corroborated by 2+ independent tools)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{confirmed_findings}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
UNVERIFIED FINDINGS  (single-source, require analyst review)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{unverified_findings}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INDICATORS OF COMPROMISE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{iocs}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MITRE ATT&CK COVERAGE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{mitre}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RECOMMENDED ACTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{recommended_actions}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AUDIT TRAIL NOTE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
All findings in this report are traceable to specific tool executions in
the session audit log. Unverified findings are explicitly labeled and MUST
NOT be treated as confirmed without additional investigation.

This report was generated by Find Evil v1.0 — an autonomous DFIR agent
built on the SANS SIFT Workstation via the Model Context Protocol.
"""


def generate_report(tool_input: dict, audit_dir: Path) -> dict:
    """Generate structured report from agent's final synthesis."""
    all_findings = tool_input.get("all_findings", [])
    case_id = tool_input.get("case_id", "UNKNOWN")
    analyst_summary = tool_input.get("analyst_summary", "")
    timeline = tool_input.get("timeline_of_attack", "No timeline provided.")
    recommended = tool_input.get("recommended_actions", [])
    severity_score = tool_input.get("severity_score", {})

    confirmed = [f for f in all_findings if f.get("corroborated")]
    unverified = [f for f in all_findings if not f.get("corroborated")]

    all_iocs: list[dict] = []
    mitre_seen: dict[str, str] = {}

    for f in all_findings:
        for ioc in f.get("iocs", []):
            all_iocs.append(ioc)
        if mitre := f.get("mitre"):
            tid = mitre.get("technique_id", "")
            if tid and tid not in mitre_seen:
                mitre_seen[tid] = f"{tid} — {mitre.get('technique_name', '')} ({mitre.get('tactic', '')})"

    def _fmt_finding(f: dict, idx: int) -> str:
        conf = f.get("confidence", "UNKNOWN")
        sev = f.get("severity", "UNKNOWN")
        corr = "✓ CORROBORATED" if f.get("corroborated") else "⚠ UNVERIFIED"
        lines = [
            f"  [{idx}] [{sev}] [{conf}] {corr}",
            f"      {f.get('description', '')}",
            f"      Source: {', '.join(f.get('source_tools', ['unknown']))}",
            f"      ID: {f.get('id', 'N/A')}",
        ]
        if detail := f.get("corroboration_detail"):
            lines.append(f"      Corroboration: {detail}")
        return "\n".join(lines)

    confirmed_text = "\n\n".join(_fmt_finding(f, i + 1) for i, f in enumerate(confirmed)) or "  None"
    unverified_text = "\n\n".join(_fmt_finding(f, i + 1) for i, f in enumerate(unverified)) or "  None"

    ioc_text = ""
    for ioc_type in ("ip", "domain", "hash", "process", "file_path", "registry_key"):
        typed = [i for i in all_iocs if i.get("type") == ioc_type]
        if typed:
            ioc_text += f"\n  {ioc_type.upper()}:\n"
            for ioc in typed:
                ioc_text += f"    • {ioc['value']}  ({ioc.get('context', '')})\n"

    mitre_text = "\n".join(f"  • {v}" for v in mitre_seen.values()) or "  None mapped"
    actions_text = "\n".join(f"  {i + 1}. {a}" for i, a in enumerate(recommended)) or "  See severity score"

    report_text = REPORT_TEMPLATE.format(
        case_id=case_id,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        risk_level=severity_score.get("risk_level", "UNKNOWN"),
        total_findings=len(all_findings),
        corroborated_count=len(confirmed),
        unverified_count=len(unverified),
        analyst_summary=analyst_summary,
        timeline=timeline,
        confirmed_findings=confirmed_text,
        unverified_findings=unverified_text,
        iocs=ioc_text or "  None extracted",
        mitre=mitre_text,
        recommended_actions=actions_text,
    )

    # Write both text and JSON versions
    report_dir = audit_dir / "reports"
    report_dir.mkdir(exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

    text_path = report_dir / f"{case_id}_{ts}.txt"
    json_path = report_dir / f"{case_id}_{ts}.json"

    text_path.write_text(report_text)
    json_path.write_text(json.dumps({
        "case_id": case_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "risk_level": severity_score.get("risk_level", "UNKNOWN"),
        "all_findings": all_findings,
        "iocs": all_iocs,
        "mitre_techniques": list(mitre_seen.keys()),
        "analyst_summary": analyst_summary,
        "timeline": timeline,
        "recommended_actions": recommended,
    }, indent=2))

    print(report_text)
    print(f"\n[find-evil] Report written to: {text_path}", flush=True)

    return {
        "report_path": str(text_path),
        "json_path": str(json_path),
        "risk_level": severity_score.get("risk_level", "UNKNOWN"),
        "total_findings": len(all_findings),
        "corroborated": len(confirmed),
        "unverified": len(unverified),
    }
